In [24]:
import numpy as np
a = np.array([1,2,3])
a

array([1, 2, 3])

In [6]:
print(a)

[1 2 3]


In [7]:
type(a)

numpy.ndarray

In [8]:
a.shape

(3,)

In [10]:
b = np.array([[1,2,3],[4,5,6]])

In [11]:
b

array([[1, 2, 3],
       [4, 5, 6]])

In [18]:
b.shape

(2, 3)

In [19]:
c1 = np.array([0,1,2,3,4,5])

In [20]:
c1

array([0, 1, 2, 3, 4, 5])

In [23]:
c2 = c1.reshape((2,3))

In [24]:
c2

array([[0, 1, 2],
       [3, 4, 5]])

In [29]:
c3 = c2.reshape((1,6))

In [28]:
c3

array([[0, 1, 2, 3, 4, 5]])

In [31]:
c4 = c2.ravel()

In [32]:
c4

array([0, 1, 2, 3, 4, 5])

In [33]:
c5 = c2.flatten()

In [34]:
c5

array([0, 1, 2, 3, 4, 5])

In [35]:
a.dtype

dtype('int32')

In [36]:
d = np.array([1,2], dtype=np.int16)
d

array([1, 2], dtype=int16)

In [37]:
d.dtype

dtype('int16')

In [38]:
d.astype(np.float16)

array([1., 2.], dtype=float16)

In [39]:
a

array([1, 2, 3])

In [40]:
a[0]

1

In [41]:
a[1:]

array([2, 3])

In [42]:
a[-1]

3

In [43]:
b

array([[1, 2, 3],
       [4, 5, 6]])

In [44]:
b[0]

array([1, 2, 3])

In [45]:
b[1,0]

4

In [46]:
b[:,2]

array([3, 6])

In [47]:
b[1,:]

array([4, 5, 6])

In [48]:
b[0,1:]

array([2, 3])

In [29]:
a

array([1, 2, 3])

In [50]:
a[2] = 4

In [51]:
a

array([1, 2, 4])

In [ ]:
b

NameError: name 'b' is not defined

In [53]:
b[1,2]

6

In [6]:
b[1,2] = 7

NameError: name 'b' is not defined

In [5]:
b

NameError: name 'b' is not defined

In [56]:
b[:,2] = 8
b

array([[1, 2, 8],
       [4, 5, 8]])

In [30]:
a1 = a

In [32]:
a1

array([1, 2, 3])

In [59]:
a1[1] = 5

In [60]:
a1

array([1, 5, 4])

In [62]:
a2 = a.copy()
a2

array([1, 5, 4])

In [63]:
a2[0] = 6
a2

array([6, 5, 4])

In [64]:
a

array([1, 5, 4])

In [65]:
c2

array([[0, 1, 2],
       [3, 4, 5]])

In [66]:
c3 = c2.ravel()
c4 = c2.flatten()
c3[0] = 6
c4[1] = 7

In [67]:
c3

array([6, 1, 2, 3, 4, 5])

In [68]:
c4

array([0, 7, 2, 3, 4, 5])

In [69]:
c2

array([[6, 1, 2],
       [3, 4, 5]])

In [70]:
py_list1 = [0,1]
py_list2 = py_list1[:]
py_list2[0] = 2
print(py_list1)
print(py_list2)

[0, 1]
[2, 1]


In [72]:
np_array1 = np.array([0,1])
np_array2 = np_array1[:]
np_array2[0] = 2
print(np_array1)
print(np_array2)

[2 1]
[2 1]


In [2]:
import numpy as np
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [6]:
np.arange(1, 11, 2)

array([1, 3, 5, 7, 9])

In [ ]:
rng = np.random.default_rng()
f = rng.random((3, 2))
f

array([[0.4917016 , 0.12306324],
       [0.8756861 , 0.32876557],
       [0.19626578, 0.36239241]])

In [13]:
rng = np.random.default_rng(123)
f =rng.random((3, 2))
f

array([[0.68235186, 0.05382102],
       [0.22035987, 0.18437181],
       [0.1759059 , 0.81209451]])

In [28]:
rng = np.random.default_rng(123)
rng.integers(1, 10)

1

In [43]:
rng = np.random.default_rng(123)
rng.integers(1, 10, size=(3, 3))

array([[1, 7, 6],
       [1, 9, 2],
       [3, 2, 4]], dtype=int64)

In [44]:
rng = np.random.default_rng(123)
rng.uniform(0.0, 0.5, size=(3, 3))

array([[0.68235186, 0.05382102, 0.22035987],
       [0.18437181, 0.1759059 , 0.81209451],
       [0.923345  , 0.2765744 , 0.81975456]])

In [2]:
import numpy as np

rng =  np.random.default_rng(123)
rng.uniform(size=(4 , 3))

array([[0.68235186, 0.05382102, 0.22035987],
       [0.18437181, 0.1759059 , 0.81209451],
       [0.923345  , 0.2765744 , 0.81975456],
       [0.88989269, 0.51297046, 0.2449646 ]])

In [3]:
rng = np.random.default_rng(123)
rng.standard_normal(size=(4, 2))

array([[-0.98912135, -0.36778665],
       [ 1.28792526,  0.19397442],
       [ 0.9202309 ,  0.57710379],
       [-0.63646365,  0.54195222]])

In [8]:
rng = np.random.default_rng(123)
rng.normal(50, 10, 3)

array([40.1087865 , 46.32213349, 62.87925261])

In [10]:
rng = np.random.default_rng(123)
rng.normal(50, 10, size=(4, 3))

array([[40.1087865 , 46.32213349, 62.87925261],
       [51.93974419, 59.202309  , 55.77103791],
       [43.63536354, 55.4195222 , 46.83404549],
       [46.77610884, 50.97167319, 34.74069593]])

In [11]:
np.zeros(3)

array([0., 0., 0.])

In [12]:
np.zeros((2, 3)) 

array([[0., 0., 0.],
       [0., 0., 0.]])

In [13]:
np.ones(2)

array([1., 1.])

In [14]:
np.ones((3, 4)) 

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [15]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [16]:
np.full(3, 3.14)

array([3.14, 3.14, 3.14])

In [18]:
np.full((2, 4), np.pi)

array([[3.14159265, 3.14159265, 3.14159265, 3.14159265],
       [3.14159265, 3.14159265, 3.14159265, 3.14159265]])

In [19]:
np. nan

nan

In [20]:
np.array([1, 2, np.nan])

array([ 1.,  2., nan])

In [21]:
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [22]:
np.linspace(0, np.pi, 21)

array([0.        , 0.15707963, 0.31415927, 0.4712389 , 0.62831853,
       0.78539816, 0.9424778 , 1.09955743, 1.25663706, 1.41371669,
       1.57079633, 1.72787596, 1.88495559, 2.04203522, 2.19911486,
       2.35619449, 2.51327412, 2.67035376, 2.82743339, 2.98451302,
       3.14159265])

In [24]:
l = np.array([2, 2, 6, 1, 3])
np.diff(l)

array([ 0,  4, -5,  2])

In [33]:
print(a)
print(a1)

[1 2 3]
[1 2 3]


In [34]:
np.concatenate([a, a1])

array([1, 2, 3, 1, 2, 3])

In [37]:
b1 = np.array([[10], [20]])
b1

array([[10],
       [20]])

In [39]:
np.concatenate([b, b1], axis=1)

array([[ 1,  2,  3, 10],
       [ 4,  5,  6, 20]])

In [40]:
np.hstack([b, b1])

array([[ 1,  2,  3, 10],
       [ 4,  5,  6, 20]])

In [4]:
b2 = np.array([30, 60, 45])
b2

array([30, 60, 45])

In [12]:
b3 = np.vstack([b, b2])
b3

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [30, 60, 45]])

In [43]:
np.concatenate([b, b3],axis=0)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 1,  2,  3],
       [ 4,  5,  6],
       [30, 60, 45]])

In [15]:
first, second = np.hsplit(b3, [2])
first

array([[ 3],
       [ 6],
       [45]])

In [17]:
second

array([[ 3],
       [ 6],
       [45]])

In [19]:
first1, second1 = np.vsplit(b3, [2])
first1

array([[1, 2, 3],
       [4, 5, 6]])

In [20]:
second1

array([[30, 60, 45]])

In [21]:
b

array([[1, 2, 3],
       [4, 5, 6]])

In [22]:
b.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [25]:
a

array([1, 2, 3])

In [26]:
a[np.newaxis, :]

array([[1, 2, 3]])

In [28]:
a[:, np.newaxis]

array([[1],
       [2],
       [3]])

In [30]:
m = np.arange(0, 4)
m

array([0, 1, 2, 3])

In [31]:
n = np.arange(4, 7)
n

array([4, 5, 6])

In [33]:
xx, yy = np.meshgrid(m, n)
xx

array([[0, 1, 2, 3],
       [0, 1, 2, 3],
       [0, 1, 2, 3]])

In [34]:
yy

array([[4, 4, 4, 4],
       [5, 5, 5, 5],
       [6, 6, 6, 6]])