In [5]:
import numpy as np
a = np.array([1,2,3])
a

array([1, 2, 3])

In [6]:
print(a)

[1 2 3]


In [7]:
type(a)

numpy.ndarray

In [8]:
a.shape

(3,)

In [16]:
b = np.array([[1,2,3],[4,5,6]])

In [17]:
b

array([[1, 2, 3],
       [4, 5, 6]])

In [18]:
b.shape

(2, 3)

In [19]:
c1 = np.array([0,1,2,3,4,5])

In [20]:
c1

array([0, 1, 2, 3, 4, 5])

In [23]:
c2 = c1.reshape((2,3))

In [24]:
c2

array([[0, 1, 2],
       [3, 4, 5]])

In [29]:
c3 = c2.reshape((1,6))

In [28]:
c3

array([[0, 1, 2, 3, 4, 5]])

In [31]:
c4 = c2.ravel()

In [32]:
c4

array([0, 1, 2, 3, 4, 5])

In [33]:
c5 = c2.flatten()

In [34]:
c5

array([0, 1, 2, 3, 4, 5])

In [35]:
a.dtype

dtype('int32')

In [36]:
d = np.array([1,2], dtype=np.int16)
d

array([1, 2], dtype=int16)

In [37]:
d.dtype

dtype('int16')

In [38]:
d.astype(np.float16)

array([1., 2.], dtype=float16)

In [39]:
a

array([1, 2, 3])

In [40]:
a[0]

1

In [41]:
a[1:]

array([2, 3])

In [42]:
a[-1]

3

In [43]:
b

array([[1, 2, 3],
       [4, 5, 6]])

In [44]:
b[0]

array([1, 2, 3])

In [45]:
b[1,0]

4

In [46]:
b[:,2]

array([3, 6])

In [47]:
b[1,:]

array([4, 5, 6])

In [48]:
b[0,1:]

array([2, 3])

In [49]:
a

array([1, 2, 3])

In [50]:
a[2] = 4

In [51]:
a

array([1, 2, 4])

In [52]:
b

array([[1, 2, 3],
       [4, 5, 6]])

In [53]:
b[1,2]

6

In [54]:
b[1,2] = 7

In [55]:
b

array([[1, 2, 3],
       [4, 5, 7]])

In [56]:
b[:,2] = 8
b

array([[1, 2, 8],
       [4, 5, 8]])

In [57]:
a1 = a

In [58]:
a1

array([1, 2, 4])

In [59]:
a1[1] = 5

In [60]:
a1

array([1, 5, 4])

In [62]:
a2 = a.copy()
a2

array([1, 5, 4])

In [63]:
a2[0] = 6
a2

array([6, 5, 4])

In [64]:
a

array([1, 5, 4])

In [65]:
c2

array([[0, 1, 2],
       [3, 4, 5]])

In [66]:
c3 = c2.ravel()
c4 = c2.flatten()
c3[0] = 6
c4[1] = 7

In [67]:
c3

array([6, 1, 2, 3, 4, 5])

In [68]:
c4

array([0, 7, 2, 3, 4, 5])

In [69]:
c2

array([[6, 1, 2],
       [3, 4, 5]])

In [70]:
py_list1 = [0,1]
py_list2 = py_list1[:]
py_list2[0] = 2
print(py_list1)
print(py_list2)

[0, 1]
[2, 1]


In [72]:
np_array1 = np.array([0,1])
np_array2 = np_array1[:]
np_array2[0] = 2
print(np_array1)
print(np_array2)

[2 1]
[2 1]
